### ISSUE TITLE
No default export found in module

### ISSUE THREAD

**Issue by l4ngur** [mejiamanuel57/vue-facebook-signin-button-directive#3]
Hi, I get "No default export found in module" during compilation. There should be a "export default" keyword before "Vue.directive" declaration. Or am i missing something?

**Comment by manuelmejiaio** [comment]
Hi @l4ngur, you are right, I will fix this error today. Sorry for the inconveniences.

**Comment by l4ngur** [comment]
Great, thank you very much for your code.

**Comment by manuelmejiaio** [comment]
Hi @l4ngur, I have fixed and published the package, get the latest version here: https://www.npmjs.com/package/vue-facebook-signin-button-directive
